// WORKSTATE sha256 스탬핑 및 Projection 파일(RUNTIME-INDEX.md, HANDOFF.md) 생성기.
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;

internal static class ProjectionCli
{
    private static readonly JsonSerializerOptions WriteOptions = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    private const string GeneratedWarning =
        "<!-- GENERATED by 'dotnet run --project server -- projection'. 직접 편집하지 마라 — 다음 실행에서 덮어써진다. 원본은 docs/handoff/WORKSTATE.json 이다. -->";

    // Projection 파일은 자기 자신의 해시를 WORKSTATE에 기록하지 않는다(순환 참조 금지).
    private static readonly HashSet<string> SelfExcluded = new(StringComparer.OrdinalIgnoreCase)
    {
        "docs/context/RUNTIME-INDEX.md",
        "docs/handoff/HANDOFF.md",
    };

    // 진입점: WORKSTATE sha256 스탬핑 후 RUNTIME-INDEX.md, HANDOFF.md를 생성한다. exit 0=성공, 2=치명 오류.
    internal static int Run(string[] args)
    {
        try
        {
            var root = GitTools.FindRepoRoot();
            var workstatePath = Path.Combine(root, "docs", "handoff", "WORKSTATE.json");

            if (!File.Exists(workstatePath))
            {
                Console.Error.WriteLine("{\"error\":\"WORKSTATE.json not found\"}");
                return 2;
            }

            var workstate = JsonNode.Parse(File.ReadAllText(workstatePath))?.AsObject();
            if (workstate is null)
            {
                Console.Error.WriteLine("{\"error\":\"WORKSTATE.json is not a JSON object\"}");
                return 2;
            }

            StampHashes(root, workstate);
            WriteAtomically(workstatePath, workstate.ToJsonString(WriteOptions));

            var runtimeIndexPath = Path.Combine(root, "docs", "context", "RUNTIME-INDEX.md");
            Directory.CreateDirectory(Path.GetDirectoryName(runtimeIndexPath)!);
            File.WriteAllText(runtimeIndexPath, GenerateRuntimeIndex(workstate), new UTF8Encoding(false));

            var handoffPath = Path.Combine(root, "docs", "handoff", "HANDOFF.md");
            File.WriteAllText(handoffPath, GenerateHandoff(root, workstate), new UTF8Encoding(false));

            var result = new JsonObject
            {
                ["ok"] = true,
                ["stamped"] = CountStamped(workstate),
                ["missingFiles"] = CountMissing(workstate),
                ["runtimeIndex"] = "docs/context/RUNTIME-INDEX.md",
                ["handoff"] = "docs/handoff/HANDOFF.md",
            };
            Console.WriteLine(result.ToJsonString(WriteOptions));
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"{{\"error\":\"projection failed: {ex.Message}\"}}");
            return 2;
        }
    }

    // changedFiles 각 항목에 sha256을 계산해 채운다. 파일이 없으면 sha256=null, missing=true.
    private static void StampHashes(string root, JsonObject workstate)
    {
        var changed = workstate["changedFiles"] as JsonArray;
        if (changed is null) return;

        foreach (var node in changed.OfType<JsonObject>())
        {
            var path = node["path"]?.ToString() ?? "";
            if (string.IsNullOrWhiteSpace(path)) continue;
            if (SelfExcluded.Contains(path)) continue;

            var fullPath = Path.GetFullPath(Path.Combine(root, path));
            if (!File.Exists(fullPath))
            {
                node["sha256"] = null;
                node["missing"] = true;
            }
            else
            {
                var hash = Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(fullPath))).ToLowerInvariant();
                node["sha256"] = hash;
                if (node["missing"] is not null)
                    node.Remove("missing");
            }
        }
    }

    // tmp 파일을 먼저 쓴 뒤 원자적으로 교체해 부분 쓰기를 방지한다.
    private static void WriteAtomically(string targetPath, string content)
    {
        var tmpPath = targetPath + ".tmp";
        File.WriteAllText(tmpPath, content, new UTF8Encoding(false));
        File.Move(tmpPath, targetPath, overwrite: true);
    }

    // 해시가 채워진 항목 수를 반환한다.
    private static int CountStamped(JsonObject workstate)
    {
        var changed = workstate["changedFiles"] as JsonArray;
        return changed?.OfType<JsonObject>().Count(o => o["sha256"] is not null && o["sha256"]?.ToString() != "") ?? 0;
    }

    // sha256=null(파일 없음)인 항목 수를 반환한다.
    private static int CountMissing(JsonObject workstate)
    {
        var changed = workstate["changedFiles"] as JsonArray;
        return changed?.OfType<JsonObject>().Count(o => o["missing"]?.GetValue<bool>() == true) ?? 0;
    }

    // RUNTIME-INDEX.md 내용을 생성한다(L0 최소 상태, 20줄 이내).
    private static string GenerateRuntimeIndex(JsonObject workstate)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedWarning);
        sb.AppendLine();
        sb.AppendLine("# RUNTIME-INDEX — 현재 실행 위치 (L0)");
        sb.AppendLine();

        var phaseId = workstate["phaseId"]?.ToString() ?? "—";
        var wpId = workstate["wpId"]?.ToString() ?? "—";
        var diId = workstate["diId"]?.ToString() ?? "—";
        var status = workstate["status"]?.ToString() ?? "—";
        var updatedAt = workstate["updatedAt"]?.ToString() ?? "—";
        var blocker = workstate["blocker"]?.ToString();
        var nextActions = workstate["nextActions"] as JsonArray;

        sb.AppendLine($"| 항목 | 값 |");
        sb.AppendLine($"| --- | --- |");
        sb.AppendLine($"| phaseId | {phaseId} |");
        sb.AppendLine($"| wpId | {wpId} |");
        sb.AppendLine($"| diId | {diId} |");
        sb.AppendLine($"| status | {status} |");
        sb.AppendLine($"| updatedAt | {updatedAt} |");

        if (!string.IsNullOrWhiteSpace(blocker))
        {
            sb.AppendLine();
            sb.AppendLine($"**블로커:** {blocker}");
        }

        if (nextActions is { Count: > 0 })
        {
            sb.AppendLine();
            sb.AppendLine("**다음 작업:**");
            foreach (var action in nextActions.OfType<JsonValue>())
                sb.AppendLine($"- {action}");
        }

        return sb.ToString();
    }

    // HANDOFF.md 내용을 생성한다(사람용 인수인계 Projection).
    private static string GenerateHandoff(string root, JsonObject workstate)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedWarning);
        sb.AppendLine();
        sb.AppendLine("# HANDOFF — 인수인계 문서");
        sb.AppendLine();
        AppendHandoffHeader(sb, workstate);
        AppendHandoffChangedFiles(sb, workstate);
        AppendHandoffHistoryAndTests(sb, workstate);
        AppendHandoffFooter(sb, workstate);
        return sb.ToString();
    }

    // 현재 위치·블로커 절을 추가한다.
    private static void AppendHandoffHeader(StringBuilder sb, JsonObject workstate)
    {
        var diId = workstate["diId"]?.ToString() ?? "—";
        var status = workstate["status"]?.ToString() ?? "—";
        var phaseId = workstate["phaseId"]?.ToString() ?? "—";
        var updatedAt = workstate["updatedAt"]?.ToString() ?? "—";
        var updatedBy = workstate["updatedBy"]?.ToString() ?? "—";
        var blocker = workstate["blocker"]?.ToString();

        sb.AppendLine("## 현재 위치");
        sb.AppendLine($"- **diId**: {diId}  **phaseId**: {phaseId}  **status**: {status}");
        sb.AppendLine($"- **갱신자**: {updatedBy}  **갱신일**: {updatedAt}");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(blocker))
        {
            sb.AppendLine("## 블로커");
            sb.AppendLine($"- {blocker}");
            sb.AppendLine();
        }
    }

    // 변경 파일 목록과 해시 태그를 추가한다.
    private static void AppendHandoffChangedFiles(StringBuilder sb, JsonObject workstate)
    {
        var changed = workstate["changedFiles"] as JsonArray;
        sb.AppendLine($"## 변경 파일 ({changed?.Count ?? 0}개)");
        if (changed is null)
        {
            sb.AppendLine();
            return;
        }
        foreach (var node in changed.OfType<JsonObject>())
        {
            var path = node["path"]?.ToString() ?? "—";
            var sha = node["sha256"]?.ToString();
            var missing = node["missing"]?.GetValue<bool>() == true;
            var note = node["note"]?.ToString();

            string hashTag;
            if (missing) hashTag = "MISSING";
            else if (string.IsNullOrEmpty(sha)) hashTag = "NO-HASH";
            else hashTag = sha[..Math.Min(16, sha.Length)] + "…";

            var noteInfo = note is not null ? $" — {note}" : "";
            sb.AppendLine($"- `{path}` [{hashTag}]{noteInfo}");
        }
        sb.AppendLine();
    }

    // 완료 이력과 검증 결과 절을 추가한다.
    private static void AppendHandoffHistoryAndTests(StringBuilder sb, JsonObject workstate)
    {
        var history = workstate["history"] as JsonArray;
        if (history is { Count: > 0 })
        {
            sb.AppendLine("## 완료 이력");
            foreach (var item in history.OfType<JsonObject>())
            {
                var hId = item["diId"]?.ToString() ?? "—";
                var files = item["changedFiles"] as JsonArray;
                sb.AppendLine($"- **{hId}**: {files?.Count ?? 0}개 파일");
            }
            sb.AppendLine();
        }

        var tests = workstate["tests"] as JsonObject;
        if (tests is not null)
        {
            sb.AppendLine("## 검증 결과");
            sb.AppendLine($"- behaviorEqual: {tests["behaviorEqual"]}");
            sb.AppendLine($"- buildVerifyVerdict: {tests["buildVerifyVerdict"]}");
            sb.AppendLine($"- measureViolationsAfter: {tests["measureViolationsAfter"]}");
            sb.AppendLine();
        }
    }

    // 다음 작업·재개 전 검증·노트 절을 추가한다.
    private static void AppendHandoffFooter(StringBuilder sb, JsonObject workstate)
    {
        var nextActions = workstate["nextActions"] as JsonArray;
        if (nextActions is { Count: > 0 })
        {
            sb.AppendLine("## 다음 작업");
            foreach (var action in nextActions.OfType<JsonValue>())
                sb.AppendLine($"- {action}");
            sb.AppendLine();
        }

        sb.AppendLine("## 재개 전 검증");
        sb.AppendLine("```bash");
        sb.AppendLine("dotnet run --project server -c Release -- handoff-integrity");
        sb.AppendLine("dotnet run --project server -c Release -- measure dev-pack");
        sb.AppendLine("dotnet run --project server -c Release -- build-verify");
        sb.AppendLine("dotnet run --project server -c Release -- verify-behavior");
        sb.AppendLine("```");

        var notes = workstate["notes"]?.ToString();
        if (!string.IsNullOrWhiteSpace(notes))
        {
            sb.AppendLine();
            sb.AppendLine("## 노트");
            sb.AppendLine(notes);
        }
    }
}
